In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\muzalik\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\muzalik\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

df = pd.read_csv('C:/Users/MUZALIK/Desktop/retail customer/customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [68]:
df = pd.read_csv(r'C:\Users\MUZALIK\Desktop\retail customer\customer_shopping_behavior.csv')

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [70]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   purchase_frequency_days  10 non-null     float64
 1   frequency_of_purchases   10 non-null     str
dtypes: float64(1), str(1)
memory usage: 292.0 bytes

In [72]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [73]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [74]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [76]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [77]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [78]:
# create a column age_group
labels=['young adult','adult','Middle_age','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [79]:
df[['age','age_group']].head(10)

   age    age_group
0   55   Middle_age
1   19  young adult
2   50   Middle_age
3   21  young adult
4   45   Middle_age
5   46   Middle_age
6   63       senior
7   27  young adult
8   26  young adult
9   57   Middle_age

In [129]:
#purchase frequency days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365.0,
    'Every 3 Months':90.0
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [131]:
df[['purchase_frequency_days','frequency_of_purchases']].head(30)

    purchase_frequency_days frequency_of_purchases
0                      14.0            Fortnightly
1                      14.0            Fortnightly
2                       7.0                 Weekly
3                       7.0                 Weekly
4                     365.0               Annually
5                       7.0                 Weekly
6                      90.0              Quarterly
7                       7.0                 Weekly
8                     365.0               Annually
9                      90.0              Quarterly
10                     14.0              Bi-Weekly
11                     14.0            Fortnightly
12                     14.0            Fortnightly
13                      7.0                 Weekly
14                      7.0                 Weekly
15                     30.0                Monthly
16                     14.0              Bi-Weekly
17                     90.0              Quarterly
18                      7.0                 Weekly
19                     14.0              Bi-Weekly
20                     90.0         Every 3 Months
21                     90.0              Quarterly
22                    365.0               Annually
23                      7.0                 Weekly
24                      7.0                 Weekly
25                    365.0               Annually
26                    365.0               Annually
27                     90.0         Every 3 Months
28                     90.0         Every 3 Months
29                      7.0                 Weekly

In [82]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\muzalik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [132]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [133]:
server_name = r'SABI-21\SQLEXPRESS'      # Or your specific SQL Server instance name
database_name = 'customer_behaviour'

In [135]:
params = urllib.parse.quote_plus(
    f'DRIVER={{ODBC Driver 17 for SQL Server}};'
    f'SERVER={server_name};'
    f'DATABASE={database_name};'
    f'Trusted_Connection=yes;'
)

In [136]:
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [137]:
table_name = 'customer_shopping'    # What you want to name your new SQL table

df.to_sql(
    name=table_name, 
    con=engine, 
    if_exists='replace',            # Options: 'fail', 'replace', 'append'
    index=False                     # Set to False so Pandas doesn't turn the index into a column
)

print(f"Success! DataFrame loaded into table '{table_name}'.")

Success! DataFrame loaded into table 'customer_shopping'.